module.exports = {
  projects: [
    ,
    '<rootDir>/libs/ui',
    '<rootDir>/libs/util',
    '<rootDir>/libs/shared/elements/card',
    '<rootDir>/libs/shared/elements/post-date',
    '<rootDir>/libs/shared/elements/sygnature',
    '<rootDir>/libs/shared/elements/seo',
    '<rootDir>/libs/shared/elements/link',
    '<rootDir>/libs/shared/elements/link-list',
    '<rootDir>/libs/shared/layouts/default-app',
    '<rootDir>/libs/shared/layouts/page',
    '<rootDir>/libs/shared/modules/mobile-sidebar',
    '<rootDir>/libs/shared/modules/header',
    '<rootDir>/libs/shared/modules/footer',
    '<rootDir>/libs/shared/styles',
    '<rootDir>/apps/test',
    '<rootDir>/libs/assets',
    '<rootDir>/libs/api',
    '<rootDir>/libs/modules/category',
    '<rootDir>/libs/modules/home',
    '<rootDir>/libs/modules/layout',
    '<rootDir>/libs/modules/post',
  ],
};
