version: '3'
services:
  strapi:
    environment:
      API_URL: https://odstresowani.pl
      NODE_ENV: production
      ENV_PATH: /srv/app/.env.production
    command: yarn start

  nextjs:
    environment:
      APP_ENV: production
    command: pm2-runtime npm -- start

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        build_type: production
    ports:
      - 443:443