version: '3'
services:
  strapi:
    environment:
      API_URL: https://odstresowani.pl
      NODE_ENV: production
      ENV_PATH: /srv/app/.env.production
    command: yarn start

  nextjs:
    environment:
      APP_ENV: production
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    command: pm2-runtime npm -- start

  nginx:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    environment:
      CERTBOT_EMAIL: office@globalx.pl
      ENVSUBST_VARS: FQDN
      FQDN: odstresowani.pl
    volumes:
      - ./nginx/production:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    ports:
      - 443:443/tcp
volumes:
  letsencrypt: