version: '3'
services:
  strapi:
    environment:
      API_URL: http://localhost
      NODE_ENV: production
      ENV_PATH: /srv/app/.env.staging
    command: yarn start

  nextjs:
    environment:
      APP_ENV: staging
    command: npm run start

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        build_type: staging