version: '3'
services:
  strapi:
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    depends_on:
      - postgres
    volumes:
      - ./backend/public:/srv/app/public
    build: ./backend

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data

  nextjs:
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/app
      - /usr/app/node_modules
      - /usr/app/.next
    ports:
      - 3000:3000
    build: ./frontend

  nginx:
    depends_on:
      - nextjs
      - strapi
    ports:
      - 80:80
