version: '3'
services:
  strapi:
    environment:
      API_URL: https://odstresowani.pl
      NODE_ENV: production
      ENV_PATH: /srv/app/.env.production
    command: yarn start

  nextjs:
    environment:
      APP_ENV: production
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    command: pm2-runtime npm -- start

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        build_type: production
        CERTBOT_EMAIL: office@globalx.pl
        DOMAIN_LIST: odstresowani.pl,www.odstresowani.pl
    volumes:
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443