version: '3'
services:
  strapi:
    image: strapi/strapi
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./odstresowani-blog-backend:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data

  nextjs:
    volumes:
      - ./odstresowani-blog-frontend:/usr/app
      - /usr/app/node_modules
      - /usr/app/.next
    build:
      context: odstresowani-blog-frontend
      dockerfile: Dockerfile

  nginx:
    build: ./nginx
    ports:
      - 80:80
