version: '3'
services:
  strapi:
    environment:
      API_URL: https://odstresowani.pl
      NODE_ENV: production
      ENV_PATH: /srv/app/.env.production
    command: yarn start

  nextjs:
    environment:
      APP_ENV: production
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    command: pm2-runtime npm -- start

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        build_type: production
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"