version: '3'
services:
  strapi:
    image: strapi/strapi
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    depends_on:
      - postgres
    build: ./backend

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data

  nextjs:
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/app
      - /usr/app/node_modules
      - /usr/app/.next
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    build:
      context: frontend
      dockerfile: Dockerfile

  nginx:
    build: ./nginx
    depends_on:
      - nextjs
      - strapi
    volumes:
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
